spring:
  profiles:
    active: [ localDev ]

---
spring:
  config:
    activate:
      on-profile: localDev
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/wea_project
    username: postgres
    password: postgres
