version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:4200"
    depends_on:
      - sk01-web
    environment:
      - API_URL=http://sk01-web:80
    networks:
      - cbd-network
  sk01-web:
    container_name: sk01-web
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "/home/cerny/logs/sk01-web:/var/logs/"
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    networks:
      - cbd-network
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wea_project
    networks:
      - cbd-network
networks:
  cbd-network:
    driver: bridge
    external: true
