version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # Mapping local port 4200 to container's port 4200
    #depends_on:
      #- backend # Ensure the backend starts before the frontend
    environment:
      - API_URL=http://backend:8080 # This is the URL the frontend will use to reach the backend
  
  #backend:
    #build:
      #context: ./backend
      #dockerfile: Dockerfile
    #ports:
      #- "8080:8080"
    #environment:
      #- NODE_ENV=production

