server:
  port: 80

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres/postgres
    username: postgres
    password: postgres
auth:
  cors:
    frontendUrl: "localhost:4200"
  jwt:
    access:
      secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"
    refresh:
      secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"
scheduler:
  book:
    import:
      cron: "0 */5 * * * *"
      enabled: true
