server:
  port: 80

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres/postgres
    username: postgres
    password: postgres
auth:
  cors:
    frontendUrl: "localhost:4200"
  jwt:
    access:
      secret: "e3a62749cb3f1923567611b91b73f7e92996ff82bdabb05150d015f894f356c3"
    refresh:
      secret: "1e631403b1c7cf24924927c2f2f7aa135ac984513cfd5dd2d5c88676e9a103dc"
synchronization:
  book:
    import:
      enabled: true
